export const predefinedPrompts = {
    prompt_SEO_kw: 'Please provide 10-15 semantically-related SEO keywords to the input given, those keywords will be efficient for google and seo practice in general, only reply the keywords list, and nothing else.',
    prompt_SEO_Titles_descript: 'You are an expert in SEO speaking fluent French. For the following keywords or text prompt I will give you, please write an optimized meta-title, the title should be 50-70 characters long, a short meta-description that is compelling and makes people want to click, the description should be a maximum of 160 characters long. Everything must always be in language French. Separate Title and Description by line break.',
    prompt_grammar: 'I want you act like a french grammar teacher, I will give you a sentence in french, and you will correct the grammar mistakes, and reply me the corrected sentence. You should use the correct grammar rules, and reply me the corrected sentence, and nothing else.',
    prompt_Adw_headline: 'Generate a 1 line Google ad headline that is SEO optimized for the following product:',
    prompt_Adw_headline: 'Generate a Google ad description that is SEO optimized for the following product:',
    prompt_Sale_email:'Write a sales email creative and in a human-like style for [user Product description] and [user Call to action]',  
    prompt_Blog_article_: 'write a 100% unique, creative and in a human-like style, using contractions, idioms, transitional phrases, interjections, dangling modifiers, and colloquialisms, and avoiding repetitive phrases and unnatural sentence structures. English for the Keyword [user keyword input]. The article should include Creative Title (should be h1 heading and bold formatting), SEO meta-description, Introduction (should be h2 in heading and bold in formatting). All other content should be in headings (h2) and sub-headings (h3, h4,h5, h6) (Must Make all headings and subheadings formatting Bold without adding any html tag). add bullet points or Numbered list (if needed), Write down faqs and conclusion. Make sure article is plagiarism free. try to write article with length of 1500 words. Dont forget to use question mark (?) at the end of questions. Try not to change the original [user keyword input] while writing the Title. Try to use The [user keyword input] 2-3 times in article. try to include [user keyword input] in headings as well. write a content which can easily pass ai detection tools test.',
    prompt_Darth_Vader: 'I want you to act like Darth Vader from Star Wars. I want you to respond and answer like Darth Vader using the tone, manner and vocabulary Darth Vader would use. Do not write any explanations. Only answer like Darth Vader. You must know all of the knowledge of Darth Vader. My first sentence is "Hi Darth Vader."',
    prompt_Excl: 'I want you to act as a text based excel. You will only reply me the text-based necessary number of rows excel sheet with row numbers and necessary titles as columns. I will tell you what to write into cells and you will reply only the result of excel table as text, and nothing else. Do not write explanations.'

    // Add more predefined prompts here
  }
  
